name: Docker Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Build React frontend
      - name: Build React frontend
        working-directory: ./client
        run: |
          yarn install
          yarn build
      
      # Build Node backend
      - name: Build Node backend
        working-directory: ./server
        run: |
          yarn install
          # Assuming you have a build script for your backend
          yarn build

      # Run services
      - name: Run React frontend
        working-directory: ./client
        run: yarn start &
      
      - name: Run Node backend
        working-directory: ./server
        run: yarn start &
